#▄▀█ █░░ ▄▀█ █▀▀ █▀█ █ ▀█▀ ▀█▀ █▄█   █▀▀ █▀█ █▄░█ █▀▀ █ █▀▀
#█▀█ █▄▄ █▀█ █▄▄ █▀▄ █ ░█░ ░█░ ░█░   █▄▄ █▄█ █░▀█ █▀░ █ █▄█

#=====================================================================================                    
# Date    : 2024-04-20
# Author  : plr
#=====================================================================================

# GENERAL -----------------------------------------------------------------------

# Color-Scheme
import = ["%APPDATA%/alacritty/color-schemes/catppuccin-mocha.toml"]

[shell]
program = "ubuntu2404"

# ENV ---------------------------------------------------------------------------

[env]
TERM = "xterm-256color"

# WINDOW ------------------------------------------------------------------------

[window]
decorations = "Full"
dynamic_padding = false
opacity = 0.8

[window.dimensions]
columns = 120
lines = 25

[window.padding]
x = 10
y = 10

# SCROLLING ---------------------------------------------------------------------

[scrolling]
history = 10000
multiplier = 3

# FONT --------------------------------------------------------------------------

[font]
size = 12

[font.normal]
# family = "Source Code Pro"
family = "Hack NFM"
# family = "JetBrains Mono"
# family = "CaskaydiaCove Nerd Font"
# family = "UbuntuMono Nerd Font"
# family = "MesloLGM Nerd Font Mono"
# family = "Maple Mono NF"
style = "Regular"

[font.bold]
# family = "Source Code Pro"
family = "Hack NFM"
# family = "JetBrains Mono"
# family = "CaskaydiaCove Nerd Font"
# family = "UbuntuMono Nerd Font"
# family = "MesloLGM Nerd Font Mono"
# family = "Maple Mono NF"
#style = "Bold"

[font.italic]
# family = "Source Code Pro"
family = "Hack NFM"
# family = "JetBrains Mono"
# family = "CaskaydiaCove Nerd Font"
# family = "UbuntuMono Nerd Font"
# family = "MesloLGM Nerd Font Mono"
# family = "Maple Mono NF"
#style = "Italic"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

# COLORS --------------------------------------------------------------------------

[colors]
draw_bold_text_with_bright_colors = true

# CURSOR --------------------------------------------------------------------------

[cursor]
style = { shape = "Beam", blinking = "Off" }
blink_interval = 750
unfocused_hollow = true


# MOUSE -----------------------------------------------------------------------------

[mouse]
bindings = [
{ mouse = "Right", mods = "Control", action = "Paste" },
{ mouse = "Right", mods = "Control", action = "ExpandSelection" },
]


# KEYBOARD --------------------------------------------------------------------------

[keyboard]
bindings = [
{ key = "N", mods = "Control", action = "CreateNewWindow" },
{ key = "V", mods = "Control", action = "Paste" },
{ key = "C", mods = "Control", action = "Copy" },
{ key = "Key0", mods = "Control", action = "ResetFontSize" },
{ key = "Plus", mods = "Control", action = "IncreaseFontSize" },
{ key = "Minus", mods = "Control", action = "DecreaseFontSize" },
{ key = "F11", mods = "None", action = "ToggleFullscreen" },
{ key = "PageUp", mods = "None", action = "ScrollPageUp" },
{ key = "PageDown", mods = "None", action = "ScrollPageDown" },
{ key = "Home", mods = "Shift", action = "ScrollToTop" },
{ key = "End", mods = "Shift", action = "ScrollToBottom" },
]









