#█▀▀ █▀ █▀█ ▄▀█ █▄░█ █▀ █▀█   █▀▄▀█ ▄▀█ ▀█▀ █▀▀ █░█   █▀▀ █ █░░ █▀▀
#██▄ ▄█ █▀▀ █▀█ █░▀█ ▄█ █▄█   █░▀░█ █▀█ ░█░ █▄▄ █▀█   █▀░ █ █▄▄ ██▄

#=====================================================================================                    
# Date    : 2022-03-24
# Author  : plr
#=====================================================================================

# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  # NOTE: espanso uses YAML to define matches, so pay attention to the indentation!

  # But matches can also be dynamic:

# Print the current date -------------------------------------------------------------------------
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

# Print the current time -------------------------------------------------------------------------
  - trigger: ":time"
    replace: "{{mytime}}"
    vars:
      - name: mytime
        type: date
        params:
          format: "%H:%M:%S"


# Print the output of a shell command ------------------------------------------------------------
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"

# Wallpaper Sync ---------------------------------------------------------------------------------
  - trigger: ":ws"
    replace: "Wallpaper Sync: {{mydate}} {{mytime}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"
      - name: mytime
        type: date
        params:
          format: "%H:%M:%S"

# Mydata -----------------------------------------------------------------------------------------
  - trigger: ":myd"
    replace: "my-data-{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

# Bug Fix ----------------------------------------------------------------------------------------
  - trigger: ":bf"
    replace: "Bug Fix: {{mydate}} {{mytime}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"
      - name: mytime
        type: date
        params:
          format: "%H:%M:%S"

# Repository Update ------------------------------------------------------------------------------
  - trigger: ":ru"
    replace: "Repo Update: {{mydate}} {{mytime}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"
      - name: mytime
        type: date
        params:
          format: "%H:%M:%S"

# Time & date now --------------------------------------------------------------------------------
  - trigger: ":now"
    replace: "{{mydate}}-{{mytime}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"
      - name: mytime
        type: date
        params:
          format: "%H.%M.%S"
          
# EasyWorship Expander --------------------------------------------------------------------------------

#Sinhala Hymns

#ගීතිකාව :

  - trigger: ":h"
    replace: "ගීතිකාව :"
    
#පුන ගැයුම :

  - trigger: ":c"
    replace: "පුන ගැයුම :"
    
#අරම්භය :

  - trigger: ":s"
    replace: "අරම්භය :"    

#අවසානය :

  - trigger: ":e"
    replace: "අවසානය :"          
    
#කිතුණු ගී අංක -

  - trigger: ":nu"
    replace: "කිතුණු ගී අංක - "  


#English Hymns

#HYMN :

  - trigger: ":H"
    replace: "HYMN"
    
#පුන ගැයුම :

  - trigger: ":C"
    replace: "CHORUS"
    
#අරම්භය :

  - trigger: ":S"
    replace: "START"    

#අවසානය :

  - trigger: ":E"
    replace: "ENDING"          
    
# Sinhala Font Fixers (Unicode) -----------------------------------------------------------------------

#Sinhala Hymns

#සඟල වරහන් - අරම්භය :

  - trigger: "$"
    replace: "“"
    
#සඟල වරහන් - අවසානය :

  - trigger: "%"
    replace: "”"
            
#තනි වරහන

  - trigger: "^"
    replace: "'"

# And much more! For more information, visit the docs: https://espanso.org/docs/
